# 心跳频率, 单位秒
# 0 为关闭心跳
heartbeatInterval: 5

# 上报数据类型
# 可选: 1:string, 2:array
messagePostFormat: 2

# 设置ws-plugin需要用到的端口
wsPort: 54545

# 是否忽略云崽配置文件的仅艾特
ignoreOnlyReplyAt: false

# 是否单独添加仅艾特或前缀
# 可以为每个连接单独添加
onlyReplyAt:
  enable: false
  prefix:
    - 示例前缀1
  "ws_name":
    enable: true
    prefix:
      - 单独连接示例前缀,ws_name是对应的连接名字

# 连接服务列表
# name: 连接名字  请保证每个名字都不相同,否则会出问题
# address: 连接地址
# type: 连接类型
# reconnectInterval: 重连间隔 单位:秒
# maxReconnectAttempts: 最大连接次数 0 为无限制
# accessToken: 鉴权token
# accessKey: 鉴权token的前缀 比如Bearer 默认为Token
servers:
  - name: ws_name
    address: ws_address
    type: 1
    reconnectInterval: 5
    maxReconnectAttempts: 0
